### ISSUE TITLE
restarting results in stray socket

### ISSUE THREAD

**Issue by lukemarsden** [ClusterHQ/flocker-docker-plugin#12]
Rebooting a machine results in:

```
2015-07-05 13:31:05-0400 [-]   File "/usr/local/lib/python2.7/dist-packages/twisted/application/internet.py", line 131, in _getPort
2015-07-05 13:31:05-0400 [-]     'listen%s' % (self.method,))(*self.args, **self.kwargs)
2015-07-05 13:31:05-0400 [-]   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 405, in listenUNIX
2015-07-05 13:31:05-0400 [-]     p.startListening()
2015-07-05 13:31:05-0400 [-]   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/unix.py", line 302, in startListening
2015-07-05 13:31:05-0400 [-]     raise CannotListenError, (None, self.port, le)
2015-07-05 13:31:05-0400 [-] twisted.internet.error.CannotListenError: Couldn't listen on any:/usr/share/docker/plugins/flocker.sock: [Errno 98] Address already in use.
```

The Flocker Docker plugin should remove stale socket files.

**Comment by myechuri** [comment]
Saw a reproduction of the issue in mesos env:

```
2015-08-12 04:39:04+0000 [-] Starting factory <twisted.web.server.Site instance at 0x7fb2b24a4518>
2015-08-12 04:39:04+0000 [-] Traceback (most recent call last):
2015-08-12 04:39:04+0000 [-]   File "/usr/local/bin/twistd", line 14, in <module>
2015-08-12 04:39:04+0000 [-]     run()
2015-08-12 04:39:04+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 29, in run
2015-08-12 04:39:04+0000 [-]     app.run(runApp, ServerOptions)
2015-08-12 04:39:04+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 617, in run
2015-08-12 04:39:04+0000 [-]     runApp(config)
2015-08-12 04:39:04+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 25, in runApp
2015-08-12 04:39:04+0000 [-]     _SomeApplicationRunner(config).run()
2015-08-12 04:39:04+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 352, in run
2015-08-12 04:39:04+0000 [-]     self.postApplication()
2015-08-12 04:39:04+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/twisted/scripts/_twistd_unix.py", line 210, in postApplication
2015-08-12 04:39:04+0000 [-]     self.startApplication(self.application)
2015-08-12 04:39:04+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/twisted/scripts/_twistd_unix.py", line 397, in startApplication
2015-08-12 04:39:04+0000 [-]     service.IService(application).privilegedStartService()
2015-08-12 04:39:05+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/twisted/application/service.py", line 278, in privilegedStartService
2015-08-12 04:39:05+0000 [-]     service.privilegedStartService()
2015-08-12 04:39:05+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/twisted/application/internet.py", line 106, in privilegedStartService
2015-08-12 04:39:05+0000 [-]     self._port = self._getPort()
2015-08-12 04:39:05+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/twisted/application/internet.py", line 134, in _getPort
2015-08-12 04:39:05+0000 [-]     'listen%s' % (self.method,))(*self.args, **self.kwargs)
2015-08-12 04:39:05+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 397, in listenUNIX
2015-08-12 04:39:05+0000 [-]     p.startListening()
2015-08-12 04:39:05+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/unix.py", line 307, in startListening
2015-08-12 04:39:05+0000 [-]     raise error.CannotListenError(None, self.port, le)
2015-08-12 04:39:05+0000 [-] twisted.internet.error.CannotListenError: Couldn't listen on any:/usr/share/docker/plugins/flocker.sock: [Errno 98] Address already in use.

```

**Comment by binocarlos** [comment]
@lukemarsden I just created #21 and #22 to address this issue - I've also created a PR against the blogpost that mentions the plugin version 0.3 - https://github.com/ClusterHQ/clusterhq.github.io/pull/155
