### ISSUE TITLE
schema not supported

### ISSUE THREAD

**Issue by wallnerryan** [ClusterHQ/flocker-docker-plugin#20]
`docker run -ti -v mytestvol:/data --volume-driver=flocker   busybox sh`

```
Aug  5 11:58:48 localhost flocker-docker-plugin: 2015-08-05 11:58:48+0000 [-] path: {u'Name': u'test'}
Aug  5 11:58:48 localhost flocker-docker-plugin: 2015-08-05 11:58:48+0000 [-] "-" - - [05/Aug/2015:11:58:47 +0000] "POST /VolumeDriver.Path HTTP/1.1" 200 652 "-" "Go 1.1 package http"
Aug  5 11:58:48 localhost flocker-docker-plugin: 2015-08-05 11:58:48+0000 [-] Unhandled error in Deferred:
Aug  5 11:58:48 localhost flocker-docker-plugin: 2015-08-05 11:58:48+0000 [-] Unhandled Error
Aug  5 11:58:48 localhost flocker-docker-plugin: Traceback (most recent call last):
Aug  5 11:58:48 localhost flocker-docker-plugin: File "/usr/lib/python2.7/site-packages/treq/client.py", line 187, in request
Aug  5 11:58:48 localhost flocker-docker-plugin: bodyProducer=bodyProducer)
Aug  5 11:58:48 localhost flocker-docker-plugin: File "/usr/lib/python2.7/site-packages/twisted/web/client.py", line 1857, in request
Aug  5 11:58:48 localhost flocker-docker-plugin: deferred = self._agent.request(method, uri, headers, bodyProducer)
Aug  5 11:58:48 localhost flocker-docker-plugin: File "/usr/lib/python2.7/site-packages/twisted/web/client.py", line 1925, in request
Aug  5 11:58:48 localhost flocker-docker-plugin: deferred = self._agent.request(method, uri, headers, bodyProducer)
Aug  5 11:58:48 localhost flocker-docker-plugin: File "/usr/lib/python2.7/site-packages/twisted/web/client.py", line 1732, in request
Aug  5 11:58:48 localhost flocker-docker-plugin: d = self._agent.request(method, uri, headers, bodyProducer)
Aug  5 11:58:48 localhost flocker-docker-plugin: --- <exception caught here> ---
Aug  5 11:58:48 localhost flocker-docker-plugin: File "/usr/lib/python2.7/site-packages/twisted/web/client.py", line 1558, in request
Aug  5 11:58:48 localhost flocker-docker-plugin: endpoint = self._getEndpoint(parsedURI)
Aug  5 11:58:48 localhost flocker-docker-plugin: File "/usr/lib/python2.7/site-packages/twisted/web/client.py", line 1542, in _getEndpoint
Aug  5 11:58:48 localhost flocker-docker-plugin: return self._endpointFactory.endpointForURI(uri)
Aug  5 11:58:48 localhost flocker-docker-plugin: File "/usr/lib/python2.7/site-packages/twisted/web/client.py", line 1422, in endpointForURI
Aug  5 11:58:48 localhost flocker-docker-plugin: raise SchemeNotSupported("Unsupported scheme: %r" % (uri.scheme,))
Aug  5 11:58:48 localhost flocker-docker-plugin: twisted.web.error.SchemeNotSupported: Unsupported scheme: ''
Aug  5 11:58:48 localhost flocker-docker-plugin: 2015-08-05 11:58:48+0000 [-] path: {u'Name': u'myvol'}
Aug  5 11:58:48 localhost flocker-docker-plugin: 2015-08-05 11:58:48+0000 [-] "-" - - [05/Aug/2015:11:58:47 +0000] "POST /VolumeDriver.Path HTTP/1.1" 200 652 "-" "Go 1.1 package http"

```

Experimental version

```
# docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Experimental (client): true
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
Experimental (server): true
```

```
[root@mdm2 flocker]# systemctl status -l flocker-docker-plugin
flocker-docker-plugin.service - flocker-plugin - flocker-docker-plugin job file
   Loaded: loaded (/etc/systemd/system/flocker-docker-plugin.service; disabled)
   Active: active (running) since Wed 2015-08-05 12:03:33 UTC; 5s ago
 Main PID: 14568 (twistd)
   CGroup: /system.slice/flocker-docker-plugin.service
           └─14568 /bin/python /usr/bin/twistd -noy /opt/flocker/flocker-1.0.3/flocker-tutorial/lib/python2.7/site-packages/flockerdockerplugin/flockerdockerplugin.tac

Aug 05 12:03:33 mdm2.scaleio.local systemd[1]: Starting flocker-plugin - flocker-docker-plugin job file...
Aug 05 12:03:33 mdm2.scaleio.local systemd[1]: Started flocker-plugin - flocker-docker-plugin job file.
```

I am running this on CentOS, with VFS, but would like to get this working.

**Comment by itamarst** [comment]
A random guess: you're using an old version of Twisted, perhaps the one provided by your OS.

**Comment by wallnerryan** [comment]
Thanks itamar, will try that out. One other thing, the docs for Ubuntu say it needs AUFS, what's the hard dependency there ? Why can't I use VFS with flocker docker plugin?

-Ryan

**Comment by binocarlos** [comment]
@wallnerryan Hey - I don't think there is a hard dependency on aufs - the docs mention it to ensure folks don't use devicemapper which has had a bunch of problems.  We should update the docs I think :-)

**Comment by wallnerryan** [comment]
thanks @binocarlos , @itamarst I was running the system twisted, but when I am running flocker  and flocker-docker-plugin out of a virtual env running twisted 15.1.0 i see these errors

```
Aug  6 13:12:33 localhost systemd: Unit flocker-docker-plugin.service entered failed state.
Aug  6 13:14:47 localhost systemd: Starting flocker-plugin - flocker-docker-plugin job file...
Aug  6 13:14:47 localhost systemd: Started flocker-plugin - flocker-docker-plugin job file.
Aug  6 13:14:47 localhost flocker-docker-plugin: Traceback (most recent call last):
Aug  6 13:14:47 localhost flocker-docker-plugin: File "/opt/flocker/flocker-1.0.3/flocker-tutorial/bin/flocker-docker-plugin", line 5, in <module>
Aug  6 13:14:47 localhost flocker-docker-plugin: os.execl(twistd, "twistd", "-noy", tac)
Aug  6 13:14:47 localhost flocker-docker-plugin: File "/opt/flocker/flocker-1.0.3/flocker-tutorial/lib64/python2.7/os.py", line 312, in execl
Aug  6 13:14:47 localhost flocker-docker-plugin: execv(file, args)
Aug  6 13:14:47 localhost flocker-docker-plugin: TypeError: coercing to Unicode: need string or buffer, NoneType found
Aug  6 13:14:47 localhost systemd: flocker-docker-plugin.service: main process exited, code=exited, status=1/FAILURE
Aug  6 13:14:47 localhost systemd: Unit flocker-docker-plugin.service entered failed state.
```

Also bumped docker to 1.8 experimental, will need the above issue fixed before I try `docker run` again

```
Client:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   5b92604
 Built:        Mon Jul 20 18:36:25 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   5b92604
 Built:        Mon Jul 20 18:36:25 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
[root@mdm2 ~]# docker info
Containers: 0
Images: 0
Storage Driver: vfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 994.4 MiB
Name: mdm2.scaleio.local
ID: H5SE:Y46U:L3LO:VIRA:W2HE:QGLP:SA6E:SOE3:ZX3D:TTB3:AZW7:3555
Experimental: true
```

**Comment by wallnerryan** [comment]
seems it was an issue with the pointer to the `twistd` binary. `twistd = distutils.spawn.find_executable("twistd")` must not find the correct one.

This seems to fix it

```
sed -i 's/twistd\,/\"\/opt\/flocker\/flocker-$FLOCKERVERSION\/flocker-tools\/bin\/twistd\"\,/' /opt/flocker/flocker-1.0.3/flocker-tools/bin/flocker-docker-plugin
```

```
Aug  7 08:41:08 localhost systemd: Starting flocker-plugin - flocker-docker-plugin job file...
Aug  7 08:41:08 localhost systemd: Started flocker-plugin - flocker-docker-plugin job file.
Aug  7 08:41:11 localhost flocker-docker-plugin: 2015-08-07 08:41:11+0000 [-] Log opened.
Aug  7 08:41:11 localhost flocker-docker-plugin: 2015-08-07 08:41:11+0000 [-] twistd 15.3.0 (/opt/flocker/flocker-1.0.3/flocker-tools/bin/python2.7 2.7.5) starting up.
Aug  7 08:41:11 localhost flocker-docker-plugin: 2015-08-07 08:41:11+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
Aug  7 08:41:11 localhost flocker-docker-plugin: 2015-08-07 08:41:11+0000 [-] Site starting on '/usr/share/docker/plugins/flocker.sock'
Aug  7 08:41:11 localhost flocker-docker-plugin: 2015-08-07 08:41:11+0000 [-] Starting factory <twisted.web.server.Site instance at 0x2ffeb90>
Aug  7 08:41:11 localhost flocker-docker-plugin: 2015-08-07 08:41:11+0000 [-] Site starting on '/run/docker/plugins/flocker.sock'
```

found out this was an issue with the `flocker-docker-plugin.service` file and need to reformat to use IP address and https

```
    [Service]
    Environment=FLOCKER_CONTROL_SERVICE_BASE_URL=https://tb.scaleio.local:4523/v1
    Environment=MY_NETWORK_IDENTITY=192.168.50.13
    ExecStart=/opt/flocker/flocker-1.0.3/flocker-tools/bin/flocker-docker-plugin
```

Then I was having issues with NonTypes and figured out `adapter.py` was using `state/datasets` instead of `configuration/datasets` in a few spots, one of them was here https://github.com/ClusterHQ/flocker-docker-plugin/blob/master/flockerdockerplugin/adapter.py#L85

Then I was getting `KeyError` here https://github.com/ClusterHQ/flocker-docker-plugin/blob/master/flockerdockerplugin/adapter.py#L281 which let me change this block to 

```
                    dataset_mapping[fs]["path"] = '/flocker/%s' % dataset_mapping[fs]['dataset_id']
                    import time
                    time.sleep(12)
                    new_binds.append(dataset_mapping[fs]["path"])
```

This time sleep was because docker engine was complaining the Mount wasnt there, is wasnt, because scaleio needed to attach and flocker needed to mount before this happened.

After all this, I got it working, so @lukemarsden and @itamarst flocker-docker-plugin is working on CentOS 7 with VFS and ScaleIO Plugin. Cheers.

```
[root@mdm2 vagrant]# docker run -ti -v test6:/data --volume-driver=flocker busybox sh
/ # 
/ # ls /data/
/ # df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/mapper/centos-root
                         38.5G     11.5G     27.0G  30% /
tmpfs                   497.2M         0    497.2M   0% /dev
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                   497.2M         0    497.2M   0% /sys/fs/cgroup
/dev/scinin             102.2G     60.0M     97.0G   0% /data
/dev/mapper/centos-root
                         38.5G     11.5G     27.0G  30% /etc/resolv.conf
/dev/mapper/centos-root
                         38.5G     11.5G     27.0G  30% /etc/hostname
/dev/mapper/centos-root
                         38.5G     11.5G     27.0G  30% /etc/hosts
tmpfs                   497.2M         0    497.2M   0% /proc/kcore
tmpfs                   497.2M         0    497.2M   0% /proc/timer_stats

```
